<% if (@audience != :external) && (Origen.site_config.gem_server_pull || Origen.site_config.gem_server) -%>
<%   Array(Origen.site_config.gem_server_pull || Origen.site_config.gem_server).each do |server| -%>
source '<%= server %>'
<%   end -%>
<% else %>
source 'https://rubygems.org'
<% end -%>

gem 'origen', '>= <%= @latest_origen_version %>'

gem 'byebug'

gem 'origen_doc_helpers'
<% if @development_dependencies -%>  
  <% @development_dependencies.each do |dep| -%>
gem <%= dep.map{ |d| "\"#{d}\"" }.join(', ') %>
  <% end -%>
<% end -%>

<% if (@audience != :external) && Origen.site_config.gem_push_plugins -%>
<%   Origen.site_config.gem_push_plugins.each do |plugin| -%>
gem <%= Array(plugin).map{ |d| "\"#{d}\"" }.join(', ') %>
<%   end -%>
<% end -%>

# Uncomment these if you want to use a visual debugger (e.g. Visual Studio Code) to debug your app
#gem 'ruby-debug-ide'
#gem 'debase'
