source 'https://rubygems.org'
source 'http://origen-hub.am.freescale.net:9292'

gem "origen_core", ">= <%= @latest_origen_version %>"

gem "doc_helpers"

if RUBY_VERSION >= '2.0.0'
  gem 'byebug', '~>3.5'
else
  gem 'debugger', '~>1.6'
end
