language: ruby
rvm:
  - 2.2.2
  - 2.4.0
  - 2.5.1
script:
  - gem install bundler -v 1.17.3
  - bundle exec origen -v
  - bundle exec origen specs
  - bundle exec origen app_gen:test --regression
    #- bundle exec origen web compile --no-serve
  - bundle exec origen lint --no-correct
env:
  - ORIGEN_GEM_USE_FROM_SYSTEM=false ORIGEN_GEM_MANAGE_BUNDLER=false
