source 'https://rubygems.org'

# Specify your gem's dependencies in origen_app_generators.gemspec
gemspec

# DO NOT ADD ANY GEMS HERE, WHEN THESE GENERATORS ARE INVOKED TO GENERATE A
# NEW APPLICATION IT WILL NOT BE LAUNCHED FROM WITHIN A BUNDLED ENVIRONMENT.
#
# THEREFORE GENERATORS MUST NOT RELY ON ANY 3RD PARTY GEMS THAT ARE NOT
# PRESENT AS PART OF A STANDARD RGEN INSTALLATION - I.E. YOU CAN ONLY RELY
# ON THE GEMS THAT RGEN ITSELF DEPENDS ON.
#
# DEVELOPMENT ONLY DEPENDENCIES ARE ALLOWED AND CAN BE ADDED TO THE .GEMSPEC
# IN THE NORMAL WAY.

if RUBY_VERSION >= '2.0.0'
  gem 'byebug', '~>3.5'
else
  gem 'debugger', '~>1.6'
end
