source 'https://rubygems.org'
<% if (@audience != :external) && Origen.site_config.gem_server -%>
source '<%= Origen.site_config.gem_server %>'
<% end -%>

gem 'origen', '>= <%= @latest_origen_version %>'

gem 'origen_testers'

gem 'origen_debuggers'

gem 'origen_doc_helpers'

gem 'byebug', '~>3.5'
