<% if (@audience != :external) && Origen.site_config.gem_server -%>
<%   Array(Origen.site_config.gem_server).each do |server| -%>
source '<%= server %>'
<%   end -%>
<% else %>
source 'https://rubygems.org'
<% end -%>

gem 'origen', '>= <%= @latest_origen_version %>'

gem 'origen_testers'

gem 'origen_debuggers'

gem 'origen_doc_helpers'

gem 'byebug'

gem 'origen_updater'

# Uncomment these if you want to use a visual debugger (e.g. Visual Studio Code) to debug your app
#gem 'ruby-debug-ide'
#gem 'debase'
