source 'https://rubygems.org'
<% if (@audience != :external) && Origen.site_config.gem_server -%>
source '<%= Origen.site_config.gem_server %>'
<% end -%>

# Specify your gem's dependencies in <%= @name %>.gemspec
gemspec

<% if @audience == :external -%>
# This gem provides integration with https://coveralls.io/ to monitor
# your application's test coverage
gem 'coveralls', require: false
<% end -%>

# Only these gems should be added here
if RUBY_VERSION >= '2.0.0'
  gem 'byebug', '~>3.5'
else
  gem 'debugger', '~>1.6'
end
