<% if (@audience != :external) && (Origen.site_config.gem_server_pull || Origen.site_config.gem_server) -%>
<%   Array(Origen.site_config.gem_server_pull || Origen.site_config.gem_server).each do |server| -%>
source '<%= server %>'
<%   end -%>
<% else %>
source 'https://rubygems.org'
<% end -%>

# Only development dependencies (things your plugin needs only when it is running in its own workspace)
# should be listed here in the Gemfile
<% if @audience == :external -%>
# This gem provides integration with https://coveralls.io/ to monitor
# your application's test coverage
gem 'coveralls', require: false
<% end -%>

gem 'byebug'
gem 'ripper-tags'
gem 'origen_doc_helpers'
<% if (@audience != :external) && Origen.site_config.gem_push_plugins -%>
<%   Origen.site_config.gem_push_plugins.each do |plugin| -%>
gem <%= Array(plugin).map{ |d| "\"#{d}\"" }.join(', ') %>
<%   end -%>
<% end -%>

# Uncomment these if you want to use a visual debugger (e.g. Visual Studio Code) to debug your app
#gem 'ruby-debug-ide'
#gem 'debase'

# Specify your gem's runtime dependencies in <%= @name %>.gemspec
# THIS LINE SHOULD BE LEFT AT THE END
gemspec
