source 'https://rubygems.org'
source 'http://origen-hub.am.freescale.net:9292'

# Specify your gem's dependencies in <%= @name %>.gemspec
gemspec

# Only these gems should be added here
if RUBY_VERSION >= '2.0.0'
  gem 'byebug', '~>3.5'
else
  gem 'debugger', '~>1.6'
end
